// The DeepSeek-V4 prompt renderer's differential gate (DeepSeek-V4-Flash-0731,
// model_type deepseek_v4): our Dsv4Prompt::render + tokenizer vs the goldens
// the checkpoint's own encoder produced (tests/data/dsv4_prompt_goldens.jsonl,
// generated by tools/gen_dsv4_prompt_goldens.py — the encoder's four shipped
// cases first). Each case checks the byte-exact render AND the tokenizer ids
// of that render — the render -> tokenizer integration the service path
// uses. The corpus header cross-references the tokenizer revision; a
// different tokenizer.json refuses the run.
//
// The same corpus drives the tool-call surface in this model's DSML
// spelling (DsmlDialect::kV4) over the REAL tokenizer: every assistant
// tool-call turn of the tool cases, as the reference renders it, must be a
// turn the constrained-decoding grammar allows id by id, and the streaming
// parser must read the reference's calls back out of it.
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "common/log.hpp"

int g_argc = 0;
char** g_argv = nullptr;
#include "common/test.hpp"
#include "loaders/hf_cache.hpp"
#include "loaders/minijson.hpp"
#include "serve/frontend.hpp"
#include "text/chat_template.hpp"
#include "text/dsv4_prompt.hpp"
#include "text/tokenizer.hpp"
#include "text/tool_grammar.hpp"
#include "text/tool_parser.hpp"

namespace {

std::string golden_path(int argc, char** argv) {
  return argc > 1 ? argv[1] : "tests/data/dsv4_prompt_goldens.jsonl";
}

void require(bool cond, const std::string& what) {
  if (!cond) throw std::runtime_error(what);
}

std::string read_text_file(const std::string& path) {
  std::ifstream f(path);
  if (!f) throw std::runtime_error("cannot open " + path);
  std::ostringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

std::string escaped(const std::string& s, size_t limit = 400) {
  std::string out;
  for (size_t i = 0; i < s.size() && i < limit; ++i) {
    const char c = s[i];
    if (c == '\n') out += "\\n";
    else if (c == '\r') out += "\\r";
    else out += c;
  }
  if (s.size() > limit) out += "...";
  return out;
}

std::vector<std::string> corpus_lines(const std::string& path) {
  std::vector<std::string> out;
  std::istringstream f(read_text_file(path));
  std::string line;
  while (std::getline(f, line))
    if (!line.empty()) out.push_back(line);
  return out;
}

// The checkpoint's snapshot, or exit 2 (the gate skips without the cache).
std::string snapshot_or_skip(const dgpp::minijson::Value& header) {
  std::string model_id = std::string(header.at("model").as_string());
  if (const char* env_model = std::getenv("DGPP_TP_REAL_MODEL"); env_model && *env_model) model_id = env_model;
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("dsv4_prompt_test: model {} unavailable ({}); skipping", model_id, err);
    std::exit(2);
  }
  return snap;
}

std::string render_json(const std::string& payload) {
  const auto globals = dgpp::minijson::parse(payload);
  return dgpp::text::Dsv4Prompt::render(globals.root);
}

bool refuses(const std::string& payload, const std::string& naming) {
  try {
    (void)render_json(payload);
  } catch (const std::runtime_error& e) {
    return std::string(e.what()).find(naming) != std::string::npos;
  }
  return false;
}

}  // namespace

DGPP_TEST(dsv4_prompt_differential_goldens) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  const std::vector<std::string> lines = corpus_lines(kGoldenPath);
  require(lines.size() >= 2, "golden corpus is empty");
  const dgpp::minijson::ParseResult hp = dgpp::minijson::parse(lines[0]);
  const dgpp::minijson::Value& header = hp.root;
  const std::string snap = snapshot_or_skip(header);
  const dgpp::text::Tokenizer tok =
      dgpp::text::Tokenizer::load((std::filesystem::path(snap) / "tokenizer.json").string());
  const dgpp::serve::Dsv4Frontend frontend(&tok);
  // The API's effort strings through the frontend onto the reference's
  // three preambles (low adds nothing).
  for (const auto& [effort, preamble] : std::vector<std::pair<std::string, std::string>>{
           {"minimal", ""}, {"low", ""}, {"medium", ""},
           {"high", "Reasoning Effort: Absolute maximum with no shortcuts permitted.\n"},
           {"xhigh", "Reasoning Effort: Beyond maximum"}, {"max", "Reasoning Effort: Beyond maximum"}}) {
    const auto settings = frontend.reasoning_settings(effort);
    require(settings.effort.has_value() && settings.enable_thinking == true, "a positive effort turns thinking on: " + effort);
    const std::string payload = R"({"messages":[{"role":"user","content":"Hi"}],"reasoning_effort":")" + *settings.effort + "\"}";
    const auto globals = dgpp::minijson::parse(payload);
    const std::string render = frontend.render_chat(globals.root);
    const std::string bos = dgpp::text::Dsv4Prompt::kBos;
    require(render == bos + preamble + render.substr(bos.size() + preamble.size()) &&
                (preamble.empty() ? render.find("Reasoning Effort") == std::string::npos
                                  : render.compare(bos.size(), preamble.size(), preamble) == 0),
            "API effort maps to the native DeepSeek-V4 preamble: " + effort);
    require(render.size() > 8 && render.compare(render.size() - 7, 7, "<think>") == 0, "the reply opens in the reasoning: " + effort);
  }
  require(frontend.reasoning_settings("none").enable_thinking == false && !frontend.reasoning_settings("none").effort,
          "DeepSeek none uses native chat mode");
  // The markers: this tokenizer shares the ｜DSML｜ tag token with V4.1's and
  // has no <｜System｜>; the frontend states the V4 spelling.
  {
    const dgpp::text::ChatMarkers mk = frontend.markers();
    require(mk.tool_format() == dgpp::text::ToolFormat::kDsml && mk.dsml_dialect == dgpp::text::DsmlDialect::kV4,
            "the frontend states the DeepSeek-V4 DSML dialect");
    require(!mk.dsml_namespaces(), "the V4 dialect has no tool namespaces");
    require(dgpp::text::ChatMarkers::from_tokenizer(tok).dsml_dialect == dgpp::text::DsmlDialect::kV41,
            "the tokenizer alone leaves the default dialect (never guessed)");
    require(mk.reasoning_available() && mk.think_open.available(), "the reasoning markers");
    require(mk.role_markers.size() == 2 && mk.role_markers[0].text == "<｜User｜>" && mk.role_markers[1].text == "<｜Assistant｜>",
            "the turn markers are <｜User｜> and <｜Assistant｜> (no <｜System｜> in this tokenizer)");
    require(frontend.boundary_token_ids().size() == 2, "the prefix cache's boundary ids");
    for (const char* knob : {"enable_thinking", "thinking", "clear_thinking", "drop_thinking", "reasoning_effort"})
      require(frontend.template_reads(knob), std::string("the renderer reads ") + knob);
    require(!frontend.template_reads("preserve_thinking"), "an unknown knob is not read");
  }
  {
    char got[32];
    std::snprintf(got, sizeof(got), "%016llx", static_cast<unsigned long long>(tok.revision_hash()));
    require(std::string(header.at("tokenizer_revision").as_string()) == got,
            "golden tokenizer revision does not match this tokenizer.json — regenerate the goldens "
            "(tools/gen_dsv4_prompt_goldens.py)");
  }
  size_t checked = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const std::string name(rec.at("name").as_string());
    const dgpp::minijson::Value& kwargs = rec.at("kwargs");
    const std::string want(rec.at("render").as_string());
    const std::string rendered = [&] {
      try {
        return dgpp::text::Dsv4Prompt::render(kwargs);
      } catch (const std::exception& e) {
        throw std::runtime_error("case '" + name + "': " + e.what());
      }
    }();
    if (rendered != want) {
      size_t k = 0;
      while (k < rendered.size() && k < want.size() && rendered[k] == want[k]) ++k;
      std::printf("[FAIL] case '%s' differs at byte %zu\n  got:  %s\n  want: %s\n", name.c_str(), k,
                  escaped(rendered.substr(k > 40 ? k - 40 : 0)).c_str(), escaped(want.substr(k > 40 ? k - 40 : 0)).c_str());
      require(false, "case '" + name + "': render differs from the reference encoder's");
    }
    std::vector<int64_t> want_ids;
    for (const auto& v : rec.at("ids").items()) want_ids.push_back(v.as_int());
    const std::vector<int64_t> got_ids = tok.encode(rendered);
    require(got_ids == want_ids, "case '" + name + "': the render's ids differ from the reference tokenizer's");
    ++checked;
  }
  require(checked == static_cast<size_t>(header.at("cases").as_int()), "the corpus holds the cases its header counts");
  DGPP_LOG_INFO("dsv4 prompt differential: {}/{} cases byte-exact with matching ids", checked, lines.size() - 1);
}

// What the reference refuses (and the forms it has no rendering for) throws
// naming the field. No checkpoint needed.
DGPP_TEST(dsv4_prompt_refusals_name_the_field) {
  require(refuses(R"({"messages":[]})", "messages"), "an empty conversation");
  require(refuses(R"({"messages":[{"role":"critic","content":"x"}]})", "messages[0]: unknown role 'critic'"), "an unknown role");
  require(refuses(R"({"messages":[{"role":"user","content":"x"}],"reasoning_effort":"extreme"})", "reasoning_effort"),
          "an unknown effort");
  require(refuses(R"({"messages":[{"role":"user","content":"x"}],"reasoning_effort":"none"})", "reasoning_effort"),
          "none is the service's enable_thinking false, not an effort of the reference");
  require(refuses(R"({"messages":[{"role":"user","content":"x"}],"reasoning_effort":75})", "reasoning_effort"),
          "a numeric budget is V4.1's, not this encoder's");
  require(refuses(R"({"messages":[{"role":"user","content":"x"},{"role":"assistant","content":"","tool_calls":[)"
                  R"({"function":{"name":"f","arguments":"[1, 2]"}}]}]})",
                  "messages[1].tool_calls[0].function.arguments"),
          "arguments that are JSON but not an object");
  require(refuses(R"({"messages":[{"role":"user","content":"x"},{"role":"assistant","content":"","tool_calls":[)"
                  R"({"function":{"arguments":"{}"}}]}]})",
                  "messages[1].tool_calls[0].function.name"),
          "a call without a name");
  require(refuses(R"({"messages":[{"role":"user","content":[{"type":"image_url","image_url":{"url":"x"}}]}]})",
                  "messages[0].content[0]"),
          "an image part (the encoder is text only)");
  require(refuses(R"({"messages":[{"role":"developer","content":""}]})", "messages[0].content"), "a developer message without content");
  require(refuses(R"({"messages":[{"role":"user","content":"x","task":"summarize"}]})", "messages[0].task"), "an unknown task");
  require(refuses(R"({"messages":[{"role":"user","content":"x"}],"tools":{"name":"f"}})", "tools"), "tools that are not an array");
  require(refuses(R"({"messages":[{"role":"user","content":"x"}],"tools":[{"type":"function"}]})", "tools[0].function"),
          "a tool entry without a function");
  require(refuses(R"({"messages":[{"role":"user","content":"x"}],"enable_thinking":true,"thinking":false})", "thinking"),
          "the two spellings of the thinking switch disagreeing");
  require(refuses(R"({"messages":[{"role":"user","content":"x"}],"clear_thinking":true,"drop_thinking":false})", "drop_thinking"),
          "the two spellings of the history switch disagreeing");
  // The two renderers are different revisions of the prefix cache's key.
  require(dgpp::text::Dsv4Prompt::source_hash() != dgpp::text::Dsv41Prompt::source_hash(), "the renderer's own revision");
}

// The tool-call surface in the V4 spelling over the real tokenizer: each
// assistant tool-call turn the reference renders is (a) a turn the grammar
// allows id by id under tool_choice required, and (b) parsed back into the
// message's calls.
DGPP_TEST(dsv4_prompt_tool_turns_through_grammar_and_parser) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  const std::vector<std::string> lines = corpus_lines(kGoldenPath);
  require(lines.size() >= 2, "golden corpus is empty");
  const dgpp::minijson::ParseResult hp = dgpp::minijson::parse(lines[0]);
  const std::string snap = snapshot_or_skip(hp.root);
  const dgpp::text::Tokenizer tok =
      dgpp::text::Tokenizer::load((std::filesystem::path(snap) / "tokenizer.json").string());
  const dgpp::serve::Dsv4Frontend frontend(&tok);
  const dgpp::text::ChatMarkers markers = frontend.markers();
  int64_t eos = -1;
  for (const auto& a : tok.added_tokens())
    if (a.content == dgpp::text::Dsv4Prompt::kEos) eos = a.id;
  require(eos >= 0, "the EOS id");
  const dgpp::text::GrammarVocab vocab = dgpp::text::GrammarVocab::from_tokenizer(
      tok, {eos}, static_cast<int>(tok.max_id() + 1), dgpp::serve::Dsv4Frontend::kDsmlDialect);
  require(vocab.usable() && vocab.markers().tool_format() == dgpp::text::ToolFormat::kDsml &&
              vocab.markers().dsml_dialect == dgpp::text::DsmlDialect::kV4,
          "the grammar vocabulary states the V4 dialect");
  // The V4.1 spelling is NOT a turn of this grammar (and the default
  // dialect's vocabulary refuses the V4 one): the two never mix silently.
  const dgpp::text::GrammarVocab vocab_v41 =
      dgpp::text::GrammarVocab::from_tokenizer(tok, {eos}, static_cast<int>(tok.max_id() + 1));
  require(vocab_v41.markers().dsml_dialect == dgpp::text::DsmlDialect::kV41, "the default dialect");

  const std::vector<std::string> kCases = {"shipped_1_thinking_with_tools", "tool_call_and_result", "tool_loop_two_steps",
                                           "tool_loop_chat_mode", "parallel_calls_results_reordered",
                                           "tool_call_with_content_and_reasoning", "tool_call_without_arguments"};
  size_t turns = 0, found = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const std::string name(rec.at("name").as_string());
    if (std::find(kCases.begin(), kCases.end(), name) == kCases.end()) continue;
    ++found;
    const dgpp::minijson::Value& kwargs = rec.at("kwargs");
    const dgpp::minijson::Value& messages = kwargs.at("messages");
    const dgpp::minijson::Value& tools = kwargs.at("tools");
    dgpp::text::GrammarSpec spec;
    spec.mode = dgpp::text::GrammarSpec::Mode::kRequired;
    for (const dgpp::minijson::Value& t : tools.items()) {
      const dgpp::minijson::Value* fn = t.find("function");
      spec.tools.push_back(dgpp::text::grammar_tool_from_function(fn ? *fn : t, nullptr));
    }
    const auto render_through = [&](size_t count) {
      std::vector<dgpp::minijson::Member> g;
      for (const dgpp::minijson::Member& m : kwargs.members()) {
        if (m.key != "messages") {
          g.push_back(m);
          continue;
        }
        std::vector<dgpp::minijson::Value> ms(messages.items().begin(),
                                              messages.items().begin() + static_cast<std::ptrdiff_t>(count));
        g.push_back({"messages", dgpp::minijson::Value::make_array(std::move(ms))});
      }
      return dgpp::text::Dsv4Prompt::render(dgpp::minijson::Value::make_object(std::move(g)));
    };
    for (size_t k = 0; k < messages.items().size(); ++k) {
      const dgpp::minijson::Value& msg = messages.items()[k];
      const dgpp::minijson::Value* tcs = msg.find("tool_calls");
      if (msg.at("role").as_string() != "assistant" || tcs == nullptr || tcs->items().empty()) continue;
      // The prompt the turn answers, and the turn as the reference writes it.
      const std::string prompt = render_through(k);
      const std::string through = render_through(k + 1);
      require(through.compare(0, prompt.size(), prompt) == 0, name + ": the turn extends its prompt");
      const std::string turn = through.substr(prompt.size());
      const std::vector<int64_t> prompt_ids = tok.encode(prompt);
      const std::vector<int64_t> ids = tok.encode(turn);
      const bool opens_thinking = markers.prompt_opens_thinking(prompt_ids);
      const dgpp::minijson::Value* enable = kwargs.find("enable_thinking");
      require(opens_thinking == !(enable && !enable->as_bool(true)), name + ": the prompt opens the reasoning in thinking mode");

      dgpp::text::GrammarState grammar(&vocab, spec, opens_thinking);
      for (size_t j = 0; j < ids.size(); ++j) {
        require(grammar.allows(ids[j]), name + ": id " + std::to_string(ids[j]) + " (" + tok.decode(ids[j], false) +
                                            ") at position " + std::to_string(j) + " refused in state " +
                                            grammar.state_name());
        grammar.advance(ids[j]);
      }
      require(grammar.active() && std::string(grammar.state_name()) == "done", name + ": the grammar ends the turn at EOS, in " +
                                                                                 grammar.state_name());
      // The same ids under the V4.1 spelling's grammar die at the block's name.
      {
        dgpp::text::GrammarState other(&vocab_v41, spec, opens_thinking);
        bool refused = false;
        for (size_t j = 0; j < ids.size() && !refused; ++j) {
          refused = !other.allows(ids[j]);
          other.advance(ids[j]);
        }
        require(refused, name + ": the V4.1 spelling's grammar refuses the V4 turn");
      }

      dgpp::text::ToolCallParser::Options opts;
      opts.start_in_reasoning = opens_thinking;
      dgpp::text::ToolCallParser parser(
          markers, [&](const std::vector<int64_t>& run) { return tok.decode(run, /*skip_special_tokens=*/true); },
          dgpp::text::ToolSchemas(tools), opts);
      std::vector<dgpp::text::ToolCallParser::Event> events;
      for (const int64_t id : ids) parser.feed(id, &events);
      parser.finish(&events);
      std::string reasoning, content;
      std::vector<dgpp::text::ToolCallParser::Call> calls;
      for (const auto& ev : events) {
        using Kind = dgpp::text::ToolCallParser::Event::Kind;
        if (ev.kind == Kind::kReasoning) reasoning += ev.text;
        else if (ev.kind == Kind::kContent) content += ev.text;
        else if (ev.kind == Kind::kToolCall) calls.push_back(ev.call);
      }
      const auto text_of = [&](const char* field) {
        const dgpp::minijson::Value* v = msg.find(field);
        return v && v->is_string() ? std::string(v->as_string()) : std::string();
      };
      require(reasoning == (opens_thinking ? text_of("reasoning_content") : ""), name + ": the reasoning: '" + reasoning + "'");
      require(content == text_of("content"), name + ": the content before the block: '" + content + "'");
      require(calls.size() == tcs->items().size(), name + ": every call parsed (" + std::to_string(calls.size()) + ")");
      for (size_t c = 0; c < calls.size(); ++c) {
        const dgpp::minijson::Value& fn = tcs->items()[c].at("function");
        require(calls[c].name == fn.at("name").as_string(), name + ": the call's name: " + calls[c].name);
        const dgpp::minijson::Value& args = fn.at("arguments");
        const std::string want = args.is_string() ? std::string(args.as_string())
                                                  : dgpp::text::Value::from_minijson(args).to_json(false);
        require(calls[c].arguments == want, name + ": the call's arguments: " + calls[c].arguments + " vs " + want);
      }
      ++turns;
    }
  }
  require(found == kCases.size(), "every tool case is in the corpus");
  require(turns >= 8, "the tool-call turns were walked (" + std::to_string(turns) + ")");
  DGPP_LOG_INFO("dsv4 tool turns: {} reference turns accepted by the V4-dialect grammar and parsed back", turns);
}

int main(int argc, char** argv) {
  g_argc = argc;
  g_argv = argv;
  return dgpp::test::run_all();
}
